/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/iris-verification`; params?: Router.UnknownInputParams; } | { pathname: `/logs`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/about`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/connect-pi`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/create-pin`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/iris-scan`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/landing`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/start`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/terms`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/auth`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/iris-verification`; params?: Router.UnknownOutputParams; } | { pathname: `/logs`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/about`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/connect-pi`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/create-pin`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/iris-scan`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/landing`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/start`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/terms`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/auth${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/iris-verification${`?${string}` | `#${string}` | ''}` | `/logs${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/onboarding/about${`?${string}` | `#${string}` | ''}` | `/onboarding/connect-pi${`?${string}` | `#${string}` | ''}` | `/onboarding/create-pin${`?${string}` | `#${string}` | ''}` | `/onboarding/iris-scan${`?${string}` | `#${string}` | ''}` | `/onboarding/landing${`?${string}` | `#${string}` | ''}` | `/onboarding/start${`?${string}` | `#${string}` | ''}` | `/onboarding/terms${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/iris-verification`; params?: Router.UnknownInputParams; } | { pathname: `/logs`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/about`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/connect-pi`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/create-pin`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/iris-scan`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/landing`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/start`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/terms`; params?: Router.UnknownInputParams; };
    }
  }
}
